version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    groups:
      jekyll-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      frontend-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      workflow-actions:
        patterns: ["*"]
